# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='№ стола')),
                ('number_seats', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=2, verbose_name='Кількість місць')),
                ('board_form', models.CharField(choices=[('R', 'Прямокутний'), ('O', 'Овальний')], default='R', max_length=1, verbose_name='Форма стола')),
                ('board_length', models.DecimalField(decimal_places=2, help_text='в % від довжини залу', max_digits=5, verbose_name='Довжина стола')),
                ('board_width', models.DecimalField(decimal_places=2, help_text='в % від ширини залу', max_digits=5, verbose_name='Ширина стола')),
                ('coordinate_horizontal', models.DecimalField(decimal_places=2, help_text='в %', max_digits=5, verbose_name='Координата стола в залі по горизонталі')),
                ('coordinate_vertical', models.DecimalField(decimal_places=2, help_text='в %', max_digits=5, verbose_name='Кордината стола в залі по вертикалі')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примітка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=30, verbose_name='Назва залу')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примітка')),
                ('hall_length', models.DecimalField(decimal_places=2, help_text='в метрах', max_digits=5, verbose_name='Довжина залу')),
                ('hall_width', models.DecimalField(decimal_places=2, help_text='в метрах', max_digits=5, verbose_name='Ширина залу')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_line', models.IntegerField(verbose_name='№ позиції')),
                ('description', models.CharField(max_length=200, verbose_name='Примітка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('board_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Board', verbose_name='Стіл')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Електронна адреса')),
                ('customer_mobile', models.CharField(max_length=50, verbose_name='Контактний телефон')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата замовлення')),
                ('ordered_by_date', models.DateTimeField(verbose_name='Замовлено на дату')),
                ('description', models.CharField(max_length=200, verbose_name='Примітка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.OrderHeader', verbose_name='Замовлення'),
        ),
        migrations.AddField(
            model_name='board',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Hall', verbose_name='Зал'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('hall', 'board_number')]),
        ),
    ]
